# Stuff that is not archived in mars
#
- - stream: enfh
    type:
    - cf
    - pf
    - wp
    - cv
  - - 1
    - 2
- - stream: enfo
    type: cm
  - - 130
- - type: wp
    levtype: pl
  - - 129
    - 131
    - 132
    - 157
    - 130

- - type: wp
    levtype: sfc
  - - 121
    - 122
    - 123
    - 129
    - 151
    - 134
    - 139
    - 141
    - 142
    - 143
    - 144
    - 164
    - 165
    - 166
    - 167
    - 168
    - 169
    - 170
    - 172
    - 183
    - 186
    - 187
    - 188
    - 189
    - 201
    - 202
    - 228
    - 236
    - 39
    - 40
    - 41
    - 42
    - 49
    - 59

